### ISSUE TITLE
Mass Scrobbling Invalid Method Signature Supplied

### ISSUE THREAD

**Issue by benferreri** [Berulacks/yams#2]
When YAMS tries to mass scrobble, last.fm returns with Error 13 Invalid Method Signature Supplied. I renamed my scrobbles.cache and created an empty dummy file to replace it, and regular scrobbling (one track at a time) worked completely fine. Here is the debug info:
[https://pastebin.com/VVNQwDda](https://pastebin.com/VVNQwDda)

**Comment by Berulacks** [comment]
Could you post the `scrobbles.cache`? I was having a similar issue with multiple track numbers being reported by mpd, fixed it in `master`, but didn't make a release for it just yet - are you running off of the `pip3` version?

**Comment by Berulacks** [comment]
Okay @benferreri , I've pushed a commit to `master` that should fix your issue. Could you test it and report back? (if so, I'll upload to PyPi/AUR as well) I've also cranked up the output of the debug loglevel (now we print all requests and responses), so that should help find the issue if it doesn't work. 

I think your problem was that one of your tracks had 3 artists registered in mpd, and Last.fm doesn't support receiving 3 artists in an API call. I've made a global fix for all params going out (as I had previously had the same issue with track numbers) so that we always send one value. Fingers crossed it works :crossed_fingers: 

Edit: I've since made a release as well, so you can upgrade via `pip install --upgrade YAMscrobbler` or the AUR as well

**Comment by benferreri** [comment]
Awesome, it works perfectly now. Thank you!
